---
title: "Rosseel 2017 Tutorial"
author: "Can Serif Mekik"
date: "2018-03-30"
output: 
  html_notebook:
    toc: true
    toc_depth: 3
---

# Setup

```{r}
library(lavaan)
```


# Example 1

```{r}
 HS.model<-'
   visual =~ x1 + x2 + x3 
  textual =~ x4 + x5 + x6
    speed =~ x7 + x8 + x9'
fit <- cfa(HS.model, data=HolzingerSwineford1939)
summary(fit, fit.measures=TRUE)
```

# Example 2

```{r}
model.PD <- '
  # measurement model
    ind60 =~ x1 + x2 + x3
    dem60 =~ y1 + y2 + y3 + y4
    dem65 =~ y5 + y6 + y7 + y8
  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60
  # residual correlations
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'
fit.PD <- sem(model.PD, data=PoliticalDemocracy)
summary(fit.PD, standardized=TRUE)
```

# More about syntax

## Orthogonalization

```{r}
fit.HS.ortho <- cfa(HS.model,
                    data = HolzingerSwineford1939,
                    orthogonal = TRUE)
summary(fit.HS.ortho, standardized=T)
```

## Set Variances of LV to 1

```{r}
fit.HS.std.lv <- cfa(HS.model,
                     data = HolzingerSwineford1939,
                     std.lv = TRUE)
summary(fit.HS.std.lv)
```

## Modifiers

### Starting Values

```{r}
model.HS.start <- "
  visual  =~ x1 + start(0.8)*x2 + start(1.2)*x3
  textual =~ x4 + start(0.5)*x5 + start(1.0)*x6
  speed   =~ x7 + start(0.7)*x8 + start(1.8)*x9
"
fit.HS.start <- cfa(model.HS.start, data=HolzingerSwineford1939)
summary(fit.HS.start, fit.measures=TRUE)
```

### Parameter Labels

```{r}
coef(fit.PD)

model.PD.labeled <- '
  # latent variable definitions
    ind60 =~ x1 + x2 + myLabel*x3
    dem60 =~ y1 + y2 + y3 + y4
    dem65 =~ y5 + y6 + y7 + y8
  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60
  # residual (co)variances
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'
fit.PD.labeled <- sem(model.PD.labeled,
                      data = PoliticalDemocracy)
coef(fit.PD.labeled)
```

## Constraints

### Equality

Two ways.

#### Identical labels
```{r}
model.HS.eq.1 <- '
  visual  =~ x1 + v2*x2 + v2*x3 
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
'

fit.HS.eq.1 <- cfa(model.HS.eq.1, data=HolzingerSwineford1939)
summary(fit.HS.eq.1, fit.measures=TRUE)
```

#### Using equal function

```{r}
model.HS.eq.2 <- '
  visual  =~ x1 + x2 + equal("visual=~x2")*x3 
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
'

fit.HS.eq.2 <- cfa(model.HS.eq.2, data=HolzingerSwineford1939)
summary(fit.HS.eq.2, fit.measures=TRUE)
```

### Nonlinear equality and inequality constraints

```{r}
set.seed(1234)
Data <- data.frame(y = rnorm(100),
                   x1 = rnorm(100),
                   x2 = rnorm(100),
                   x3 = rnorm(100))
model <- 'y ~ b1*x1 + b2*x2 + b3*x3 '
fit <- sem(model, data=Data)
coef(fit)
```

```{r}
model.constr <- ' # model with labeled parameters
                    y ~ b1*x1 + b2*x2 + b3*x3
                  # constraints
                    b1 == (b2 + b3)^2
                    b1 > exp(b2 + b3) '
fit <- sem(model.constr, data=Data)
coef(fit)
```

# Bringing in the means

Two ways.

```{r}
model.HS.means.1 <- '
# three-factor model
   visual =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
# intercepts
  x1 ~ 1
  x2 ~ 1 
  x3 ~ 1
  x4 ~ 1
  x5 ~ 1
  x6 ~ 1
  x7 ~ 1
  x8 ~ 1
  x9 ~ 1
'
fit <- cfa(model.HS.means.1,
           data = HolzingerSwineford1939)
summary(fit)
```

Easier:

```{r}
fit <- cfa(HS.model,
           data = HolzingerSwineford1939,
           meanstructure=T)
summary(fit)
```

```{r}
model.HS.fixed.intercepts <- '
# three-factor model 
  visual =~ x1 + x2 + x3 
  textual =~ x4 + x5 + x6 
  speed =~x7+x8+x9
# intercepts with fixed values
  x1 + x2 + x3 + x4 ~ 0.5*1'
fit <- cfa(model.HS.fixed.intercepts,
           data = HolzingerSwineford1939)
summary(fit)
```

# Multiple Groups